name              'ms_dotnet35'
maintainer        'Tim Smith'
maintainer_email  'tsmith@llnw.com'
license           'Apache 2.0'
license           'All rights reserved'
description       'Installs Microsoft .NET Framework 3.5'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version           '1.0.1'
supports          'windows'
depends           'windows'
